"""
Django settings for coupon_management_backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pq=rr05zvb$^ljcv-z%cqh(r&0f6b%v-@ybl=i57bxvn^ui%mg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["13.61.4.68","chcanimalhealth.in","*"]

#EMAIL SETTINGS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Update as per your email provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'pdate73@gmail.com'
EMAIL_HOST_PASSWORD = 'Pratik#123'


# Application definition
INSTALLED_APPS = [
    'jazzmin',  #
    "django_light",
   'django_nvd3',
    'django.contrib.humanize',

    

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #manual changes
    "vso_app",
    "manager_app",
    'rest_framework',
    'rest_framework.authtoken',

    'whitenoise.runserver_nostatic' #static content loading
    

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #added by Onkar for static conent 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    
]

ROOT_URLCONF = 'coupon_management_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coupon_management_backend.wsgi.application' 


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql',
       'NAME': 'coupon_management_backend',
       'USER': 'mysuperuser',
       'PASSWORD': 'mysuperuser',
       'HOST': 'coupon-management-backend-database.czycmuqk6t0c.eu-north-1.rds.amazonaws.com',
       'PORT': '5432',
   }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



#Manualy


CSRF_TRUSTED_ORIGINS = [
    'https://chcanimalhealth.in',  # Add your domain here
    'https://www.chcanimalhealth.in',  # Include www if applicable
]


REST_FRAMEWORK = {
    
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    
}



JAZZMIN_SETTINGS = {
    # Basic Settings
    "site_title": "Coupon Management Admin",
    "site_header": "Coupon Management System",
    "welcome_sign": "Welcome to the Coupon Management Admin Panel",
    #"site_logo": "your_logo.png",  # Ensure this file is in your static directory
    "login_logo": None,  # Optional: Add a separate logo for the login page
    "login_logo_dark": None,  # Optional: Logo for dark mode
    "show_sidebar": True,
    "navigation_expanded": True,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "show_ui_builder": True,  # Adds a UI builder option in the menu

    # UI Tweaks
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["vso_app", "auth"],

    # Side Menu Configuration
    "topmenu_links": [
        # Master Menu
        {
            "label": "Master",
            "icon": "fas fa-database",
            "children": [
                {
                    "label": "Staff",
                    "icon": "fas fa-users",
                    "children": [
                        {"model": "manager_app.managerpersonaldetails", "label": "Manager Personal Info"},
                        {"model": "vso_app.vsopersonaldetails", "label": "VSO Personal Info"},
                    ],
                },
                {"model": "vso_app.product", "label": "Products"},
                {"model": "vso_app.doctorpersonaldetails", "label": "Client (Doctor Personal Info)"},
            ],
        },
        # Transactions Menu
        {
            "label": "Transactions",
            "icon": "fas fa-exchange-alt",
            "children": [
                {"model": "vso_app.transaction", "label": "Transactions"},
                {"model": "vso_app.transactiondetail", "label": "Transaction Details"},
                {"model": "vso_app.stocktransaction", "label": "Stock Transactions"},
                {"model": "vso_app.creditrepayment", "label": "Credit Repayments"},
                {"model": "vso_app.creditrepaymentdetail", "label": "Credit Repayment Details"},
            ],
        },
        # Reports Menu
        {
            "label": "Reports",
            "icon": "fas fa-chart-bar",
            "children": [
                {
                    "label": "Settlements",
                    "icon": "fas fa-handshake",
                    "children": [
                        {"model": "vso_app.settlement", "label": "Product Settlements"},
                        {"model": "vso_app.gifts", "label": "Gifts"},
                    ],
                },
                {"model": "vso_app.coupon", "label": "Coupons"},
                {"model": "vso_app.vsoproductstock", "label": "VSO Product Stock"},
                {
                    "label": "Bonus",
                    "icon": "fas fa-gift",
                    "children": [
                        {"model": "vso_app.bonusrecords", "label": "Bonus Records"},
                        {"model": "vso_app.bonussettlement", "label": "Bonus Settlements"},
                    ],
                },
                {
                    "label": "Credits",
                    "icon": "fas fa-credit-card",
                    "children": [
                        {"model": "vso_app.doctorcredit", "label": "Doctor Credit"},
                        {"model": "vso_app.creditrepayment", "label": "Credit Repayments"},
                    ],
                },
            ],
        },
    ],

    # Icon Customizations
    "icons": {
        "vso_app.managerpersonaldetails": "fas fa-user-tie",
        "vso_app.vsopersonaldetails": "fas fa-user",
        "vso_app.product": "fas fa-box",
        "vso_app.doctorpersonaldetails": "fas fa-user-md",
        "vso_app.transaction": "fas fa-file-invoice",
        "vso_app.transactiondetail": "fas fa-file-invoice-dollar",
        "vso_app.stocktransaction": "fas fa-warehouse",
        "vso_app.creditrepayment": "fas fa-money-check",
        "vso_app.creditrepaymentdetail": "fas fa-money-bill",
        "vso_app.settlement": "fas fa-check",
        "vso_app.gifts": "fas fa-gift",
        "vso_app.coupon": "fas fa-ticket-alt",
        "vso_app.vsoproductstock": "fas fa-boxes",
        "vso_app.bonusrecords": "fas fa-gem",
        "vso_app.bonussettlement": "fas fa-hand-holding-usd",
        "vso_app.doctorcredit": "fas fa-user-plus",
    },

    # Related Link Settings
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
    },

    # Footer
    "site_brand": "Coupon Management System",
    "copyright": "Copyright © 2025 Coupon Management Inc.",
    "powered_by": "Django Jazzmin",


    "search_model": "vso_app.product",
    "language_chooser": False,
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": True,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}



AWS_ACCESS_KEY_ID = 'AKIAWIJIULG7NVIRAGEA'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'coupon-management-backend'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'eu-north-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERITY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'