# Generated by Django 4.2 on 2025-01-04 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bonus_points', models.PositiveIntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_records', to='manager_app.managerpersonaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_points', models.IntegerField()),
                ('current_points', models.IntegerField(default=0)),
                ('date_collected', models.DateField(auto_now=True)),
                ('time_collected', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('redeemed', 'Redeemed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CreditRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_repaid', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPersonalDetails',
            fields=[
                ('doctor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_type', models.CharField(choices=[('redeemed', 'Redeemed'), ('sampled', 'Sampled')], max_length=100)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='No description available')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_points', models.IntegerField(default=0)),
                ('coupon_value', models.IntegerField(default=0)),
                ('bonus_points', models.IntegerField(default=0)),
                ('sample_points', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='VSOPersonalDetails',
            fields=[
                ('vso_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vsos/')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_app.managerpersonaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='VSOProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.product')),
                ('vso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.vsopersonaldetails')),
            ],
            options={
                'unique_together': {('vso', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_points_used', models.IntegerField()),
                ('date_transaction', models.DateField(auto_now=True)),
                ('time_transaction', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('redeemed', 'Redeemed'), ('sampled', 'Sampled'), ('credits', 'Credits'), ('debits', 'Debits')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.doctorpersonaldetails')),
                ('vso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.vsopersonaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_quantity', models.IntegerField(default=0)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('collected', 'Collected'), ('redeemed', 'Redeemed'), ('sampled', 'Sampled')], default='redeemed', max_length=10)),
                ('vso_product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='vso_app.vsoproductstock')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_settled_value', models.IntegerField()),
                ('credit_borrowed_points', models.IntegerField()),
                ('remaining_points_value', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_type', models.CharField(choices=[('redeemed', 'Redeemed'), ('sampled', 'Sampled')], max_length=100)),
                ('date_settled', models.DateField(auto_now_add=True)),
                ('time_settled', models.TimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.doctorpersonaldetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.transaction')),
                ('vso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.vsopersonaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=100)),
                ('gift_price', models.IntegerField()),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.settlement')),
            ],
        ),
        migrations.AddField(
            model_name='doctorpersonaldetails',
            name='vso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vso_app.vsopersonaldetails'),
        ),
        migrations.CreateModel(
            name='DoctorCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_points', models.IntegerField()),
                ('repaid_points', models.IntegerField(default=0)),
                ('repay_status', models.BooleanField(default=False)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('date_repaid', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.doctorpersonaldetails')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRepaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_repaid', models.IntegerField()),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vso_app.coupon')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.product')),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.creditrepayment')),
            ],
        ),
        migrations.AddField(
            model_name='creditrepayment',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.doctorcredit'),
        ),
        migrations.AddField(
            model_name='creditrepayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.transaction'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.doctorpersonaldetails'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.transaction'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='vso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.vsopersonaldetails'),
        ),
        migrations.CreateModel(
            name='BonusSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points_used', models.PositiveIntegerField()),
                ('remaining_bonus_points', models.PositiveIntegerField()),
                ('settlement_title', models.CharField(max_length=300)),
                ('settlement_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonusRecords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='vso_app.bonusrecords')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_settlements', to='manager_app.managerpersonaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_points', models.IntegerField()),
                ('points_used', models.IntegerField()),
                ('quantity_redeemed', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vso_app.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='vso_app.transaction')),
            ],
            options={
                'db_table': 'transaction_detail',
                'unique_together': {('transaction', 'product')},
            },
        ),
    ]
