# Generated by Django 4.2 on 2025-01-04 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerPersonalDetails',
            fields=[
                ('manager_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vso_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=15, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='managers/')),
                ('email', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
